set positional-arguments

test feature-name:
    devcontainer features test -f {{feature-name}} --skip-autogenerated

test-scenario feature-name scenario-filter:
    devcontainer features test -f {{feature-name}} --filter "{{scenario-filter}}" --skip-autogenerated

unarchive feature-name:
    mv archive/src/{{feature-name}} src/
    mv archive/test/{{feature-name}} test/

add feature-name:
    mkdir -p src/{{feature-name}} test/{{feature-name}}
    cp templates/src/* src/{{feature-name}}/
    cp templates/test/* test/{{feature-name}}/
    sed -i "s/<id>/{{feature-name}}/g" src/{{feature-name}}/*
    sed -i "s/<id>/{{feature-name}}/g" test/{{feature-name}}/*