set positional-arguments

test feature-name:
    devcontainer features test -f {{feature-name}} --skip-autogenerated

test-scenario feature-name scenario-filter:
    devcontainer features test -f {{feature-name}} --filter "{{scenario-filter}}" --skip-autogenerated
