name: "Generate and test features using Ray"
on:
  workflow_dispatch:
  push:
jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.filter.outputs.src }}
      test: ${{ steps.filter.outputs.test }}
      feature_specs: ${{ steps.filter.outputs.feature_specs }}
      hello: ${{ steps.filter.outputs.changes }} 
    steps:
      - uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        list-files: json
        id: filter
        with:
          filters: |
            src: ./src/**
            test: ./test/*
            feature_specs: ./feature_specs/**

  find-feature:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    runs-on: ubuntu-latest
    name: Find features
    outputs:
      generated_features: ${{ steps.feature-specs.outputs.generated_features }}
      all_features: ${{ steps.feature-specs.outputs.all_features }}
    steps:
      - uses: actions/checkout@v3    
      - id: feature-specs
        uses: ./.github/actions/list-features-action
        with:
          path: .

  test:
    needs: [find-feature, detect-changes]

    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3

      - name: "test changes"
        run: |
          echo '${{ needs.detect-changes.outputs.feature_specs }}'
          echo '${{ needs.detect-changes.outputs.src }}'
          echo '${{ needs.detect-changes.outputs.test }}'
          echo '${{ needs.detect-changes.outputs.hello }}'

          echo '${{ needs.detect-changes.outputs.src_files }}'
          echo '${{ needs.detect-changes.outputs.test_files }}'

          echo '${{ needs.detect-changes.outputs.hello_files }}'



      # - name: Shell Linter
      #   uses: azohra/shell-linter@v0.6.0
      #   with:
      #     path: "src/**/*.sh"
      #     severity: "error" # [style, info, warning, error]
      #   env:
      #     SHELLCHECK_OPTS: -e SC2072 # Acceptable use of decimal comparison

      # - name: "Install latest devcontainer CLI"
      #   run: npm install -g @devcontainers/cli

      # - name: "Install test requirements"
      #   run: |
      #     python3 -m pip install -r requirements-tests.txt

      # - name: "install generator"
      #   run: |
      #     pipx install cookiecutter
      #     pipx install shfmt-py

      # - name: Generate
      #   id: generate
      #   run: |
      #     set -e
      #     cd ..
      #     jq -c '.[]' <<< '${{ needs.find-feature.outputs.generated_features }}' | while read i; do
      #         cookiecutter ./features/pkgs/feature-template --overwrite-if-exists --no-input --config-file ./features/feature_specs/$(echo $i | tr -d '"').yaml 
      #     done
      #     cd features
        
      # - name: "Running tests"
      #   run: |
      #     docker pull mcr.microsoft.com/devcontainers/base:debian
      #     cd tests
      #     ray start --head --port=6379
      #     python3 -m pytest test_all_features.py -s --base_dir $GITHUB_WORKSPACE --image "mcr.microsoft.com/devcontainers/base:debian" --feature_ids '${{ needs.find-feature.outputs.all_features }}'
      #     cd ..

  test-global:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Testing global scenarios"
        run: devcontainer features test --global-scenarios-only .
