name: Test all features on main
on:
  push:
    branches: [main]
    paths:
      - src/**
      - test/**
      - tools/test.sh
      - .github/test-all-features-on-main.yml
    paths-ignore: [src/*/README.md]
jobs:
  test-all-features-on-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: tools/test.sh
