name: Test and publish features to ghcr
on:
  push:
    branches: [main]
    paths:
      - src/**
    paths-ignore:
      - src/*/README.md
concurrency:
  group: test-and-publish-features-to-ghcr
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: tools/test.sh
  publish-features-to-ghcr:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: tools/prebuild.sh
      - uses: devcontainers/action@v1
        with:
          publish-features: true
          base-path-to-features: src
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
