on:
  push:
    branches: [main, jcbhmr-initiative]
    paths: [src/**, test/**, .github/workflows/test.yml]
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: devcontainers/ci@v0.2
        with:
          runCmd: |
            tools/prebuild.sh
            devcontainer features test
