name: Test changed features on PRs
on:
  push:
    branches: [main]
    paths:
      - src/**
      - "!src/*/README.md"
      - test/**
      - .github/workflows/test-all-features.yml
  pull_request:
    branches: [main]
    paths:
      - src/**
      - "!src/*/README.md"
      - test/**
      - .github/workflows/test-all-features.yml
  schedule:
    # https://crontab.guru/once-a-week
    - cron: 0 0 * * 0
jobs:
  test-all-features:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: tools/test.sh
